### ISSUE TITLE
Et avec PowerDNS Recursor au lieu de BIND, ça donne quoi ?

### ISSUE THREAD

**Issue by HLFH** [angristan/local-dns-resolver#1]
Coucou,

Ce serait cool d'avoir le même script avec [PowerDNS Recursor](https://www.powerdns.com/recursor.html)

**Comment by angristan** [comment]
Qu'est ce que c'est exactement ? Juste le soft ou aussi les serveurs DNS ?

**Comment by HLFH** [comment]
PowerDNS Recursor, c'est uniquement la partie résolveur DNS.

**Comment by angristan** [comment]
Quel est l'intérêt ? :)

**Comment by HLFH** [comment]
L'intérêt ? Tu as fait un script dns-install.sh, tu pourrais faire un script dns-install2.sh pour que le résolveur DNS soit PowerDNS et non BIND, sachant que BIND est déconseillé d'après les Internets. Mais bon, si tu préfères te cantonner à BIND, c'est ton choix.

**Comment by angristan** [comment]
BIND est déconseillé ? Je ne savais pas.
Je vais voir comment fonctionne PowerDNS, ajouter un script ne me dérange pas :)

**Comment by HLFH** [comment]
Finalement, ça te dérange si tu fermes le ticket.

**Comment by angristan** [comment]
PowerDNS s'installe avec Mysql, et demande beaucoup plus de travail que le script actuel.
Le script actuel est très léger, fonctionne parfaitement bien et en plus je ne comprends pas l'intérêt de PowerDNS.
De plus, si ça te tient tant que ça à cœur, tu peux le faire toi même :)

**Comment by bortzmeyer** [comment]
Je ne crois pas que MySQL soit nécessaire pour PowerDNS recursor. Vous avez du confondre avec le serveur faisant autorité. 

Sinon, si on veut des performances, et avoir nettement moins de mises à jour de sécurité à faire en urgence qu'avec BIND, il y a Unbound. N'utiliser que BIND en 2015, c'est un peu comme être toujours avec sendmail pour le courrier.

**Comment by angristan** [comment]
Désolé, je ne comprends vraiment pas comment utiliser PowerDNS.

Pour les "mises à jour en urgences", ce script est fais pour Arch, il y a donc tous les jours des mises à jour. 
Veuillez excuser mon ignorance, si vous pouviez me donner des liens pour savoir pourquoi BIND est si mauvais, je suis preneur. En attandant, j'ai rajouté un script pour unbound.

Sendmail fais très bien son job, chacun ses besoins.

**Comment by HLFH** [comment]
@Angristan @bortzmeyer Comme il y a deux challengers pour le serveur web contre Apache que sont Nginx et maintenant h2o, il y a bien un challenger contre Sendmail qu'est Postfix, et bien un challenger contre BIND qu'est PowerDNS, qui permettent de sortir des sentiers battus, de revenir à une nouvelle performance. Tu peux voir le [comparatif Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_DNS_server_software). Suite et fin https://github.com/Angristan/Linux-DNS-server/pull/2 pour powerdns-recursor.

**Comment by angristan** [comment]
Sauf que Postfix c'est un serveur mail complet contrairement à sendmail qui peut fonctionner sans même toucher à la conf. 
Et Unbound se situe où enrtre BIND et PowerDNS ?

**Comment by HLFH** [comment]
Effectivement.

> Et Unbound se situe où entre BIND et PowerDNS ?

C'est un peu le n°3. Quand tu as compris que BIND, c'est devenu un peu obsolète, tu choisis généralement entre PowerDNS et Unbound.
