### ISSUE TITLE
127.0.0.1 (resolv.conf and  /etc/openvpn/server.conf) not working with OpenVPN

### ISSUE THREAD

**Issue by loadcorp** [angristan/local-dns-resolver#12]
When I put ip adress 127.0.0.1 in  /etc/openvpn/server.conf and resolv.conf then OpenVPN can't connect to any domain. But when I replace on 8.8.8.8 for example, then OpenVPN working correctly (Angristan/OpenVPN-install script).

I am using Debian 9 x64, could anybody tell me, maybe I am missing something or I must try another OS?

**Comment by angristan** [comment]
You mean when a client is connected to OpenVPN they can't resolve a domain?

**Comment by loadcorp** [comment]
Yes

**Comment by angristan** [comment]
Yes 127.0.0.1 can't work since it's localhost.

You have to make unbound listen on 10.8.0.1 (too), and accepts connections from 10.8.0.0/8 (too). Then put 10.8.0.1 in /etc/openvpn/server.conf

**Comment by loadcorp** [comment]
Could you clearify please how make unbound listen on 10.8.0.1 (too), and accepts connections from 10.8.0.0/8 (too) ?

**Comment by cezar97** [comment]
@loadcorp In `/etc/unbound/unbound.conf` make sure to have the following lines:
```
# for private LAN
access-control: 192.168.1.0/24 allow # replace with your own network config
interface: 192.168.1.2 # ip of the Debian machine
# for VPN
access-control: 10.8.0.0/24 allow
interface: 10.8.0.1
```
 In `/etc/openvpn/server.conf` as DNS set  `10.8.0.1`.
Anyway for more info and various possible setups with unbound have a look here https://calomel.org/unbound_dns.html.

**Comment by angristan** [comment]
@cezar97 Where do they mention LAN?

I would have said

```
interface: 127.0.0.1
access-control: 127.0.0.1/24 allow
```  
for the first part, but I agree for the rest. :+1:

**Comment by cezar97** [comment]
Oh, well it was only an example but yeah as it's not been requested I'll edit it. Thanks @Angristan.

**Comment by angristan** [comment]
No problem @cezar97.

To be clear @loadcorp you need this in your unbound conf:

```
interface: 127.0.0.1
access-control: 127.0.0.1/24 allow
interface: 10.8.0.1
access-control: 10.8.0.0/24 allow
```

**Comment by loadcorp** [comment]
Guys, thank you very much. Now all is working!

**Comment by angristan** [comment]
Cool! That's basically what https://github.com/Angristan/OpenVPN-install/issues/5 is about.
