### ISSUE TITLE
DNSSEC support

### ISSUE THREAD

**Issue by lanodan** [angristan/local-dns-resolver#4]
To have dnssec working with unbound I added :
trust-anchor-file: "/etc/dnssec/root-anchors.txt"
(generated/query-ed by unbound-anchor)

this is under gentoo

To test if DNSSEC is working look at the "ad" flag in dig in a DNSSEC-enabled zone (dnssec-tools.org might be a good default) and additionally if badsign-A.test.dnssec-tools.org doesn’t resolve (should send SERVFAIL)

**Comment by Angristan** [comment]
It should be enabled by default, but it doesn't work. Weird.

![screenshot_11-05-2017_b xqforlk4](https://cloud.githubusercontent.com/assets/11699655/25961695/7458a606-367b-11e7-825e-9a1cdea77ad6.png)

**Comment by angristan** [comment]
Added for the unbound scripts, but not for Arch because I don't have access to an Arch Linux install rn :/

**Comment by angristan** [comment]
Hop https://github.com/Angristan/Local-DNS-resolver/commit/36533738de5dd115c4ae8249827948d8e1eb178e
