### ISSUE TITLE
Does not work on OpenVZ Centos 7?

### ISSUE THREAD

**Issue by szkuta** [angristan/local-dns-resolver#9]
does not work for me on centos 7 (openvz)

possible?

**Comment by angristan** [comment]
Hi, could you provide more details?

**Comment by szkuta** [comment]
I have installed Local DNS Resolver and OpenVPN and DNS was 127.0.0.1 on OpenVPN but if i was connected to VPN there was always my Local DNS and if i changed to Google DNS in server.conf there was Google DNS. Maybe you can contact me by mail? So i can send server details? szkuta@omail.pro

**Comment by angristan** [comment]
This not related to the script. Closing.
